tokens_definition = {
    "COMMAND": ["."],
    "QUERY": ["?-"],
    "OPDECL": [":-op", "(", ","],
    "OPNAME": [")", "."],
    "RULE": [":-"],
    "ALTERNATIVES": [";"],
    "PRFASOC": ["fx", "fy"],
    "POFASOC": ["xf", "yf"],
    "INFASOC": ["xfx", "yfy"],
    "LEFASOC": ["yfx"],
    "RIFASOC": ["xfy"],
    "ATOM": ["'"],
    "STRUCTURE": ["(", ")"],
    "FUNCTOR": ["."],
    "ARGUMENTS": [","],
    "CHAR": ["_"],
    "NONSPECIALCHAR": ["_"],
    "NUMBERCHAR": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
    "LWRCHAR": ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"],
    "UPRCHAR": ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "_"],
    "SPECIALCHAR": ["@", "#", "$", "&", "=", "-", "+", "*", "/"],
    "PRFOP": ["?-", "not", ":-"],
    "INFOP": [":-", ";", ",", "is", "=..", "."],
    "ARIOP": ["+", "-", "*", "/", "mod", "^"],
    "RELOP": ["=", "\=", "<", "=<", ">", ">=", "=:=", "=\=", "==", "\=="],
    "LIST": ["[]", "."],
    "EASYLIST": ["[", "]"],
    "DIVIDEDLIST": ["[", "|", "]"],
    "TERMS": [","],
    "SPACER": [" ", "\n"]
}